f = ->
    throw new Error 'a'



f()